/**
 * Copyright (c) 2026 hangtiancheng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative, dirname, sep } from "node:path";
import type { Plugin } from "vite";

const PAGE_FILE = "page.tsx";

function scanPageFiles(pagesDir: string): string[] {
  const results: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) walk(fullPath);
      else if (entry.name === PAGE_FILE) results.push(fullPath);
    }
  };
  if (existsSync(pagesDir)) walk(pagesDir);
  return results.sort();
}

function toRoutePath(pagesDir: string, file: string): string {
  const relDir = relative(pagesDir, dirname(file));
  if (relDir === "") return "/";
  return "/" + relDir.split(sep).join("/");
}

function toComponentName(routePath: string): string {
  if (routePath === "/") return "Home";
  return routePath
    .slice(1)
    .split(/[-/]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function generate(pagesDir: string, outputFile: string): void {
  const pageFiles = scanPageFiles(pagesDir);
  const outputDir = dirname(outputFile);

  const imports: string[] = [];
  const entries: string[] = [];

  for (const file of pageFiles) {
    const routePath = toRoutePath(pagesDir, file);
    const name = toComponentName(routePath);

    let importPath = relative(outputDir, file).split(sep).join("/");
    if (!importPath.startsWith(".")) importPath = "./" + importPath;
    importPath = importPath.replace(/\.tsx$/, "");

    imports.push(`const ${name} = lazy(() => import("${importPath}"));`);
    entries.push(`  { path: "${routePath}", element: <${name} /> }`);
  }

  const content = [
    "// Auto-generated by vite-plugin-page-routes — DO NOT EDIT!!!",
    `import { lazy } from "react";`,
    `import type { RouteObject } from "react-router-dom";`,
    "",
    ...imports,
    "",
    "export const routes: RouteObject[] = [",
    entries.join(",\n") + ",",
    "];",
    "",
  ].join("\n");

  mkdirSync(outputDir, { recursive: true });
  writeFileSync(outputFile, content, "utf-8");
}

export default function pageRoutes(): Plugin {
  let root = process.cwd();

  return {
    name: "vite-plugin-page-routes",

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      const pagesDir = join(root, "src", "pages");
      const outputFile = join(root, "src", "generated", "routes.tsx");
      generate(pagesDir, outputFile);
    },

    configureServer(server) {
      const pagesDir = join(root, "src", "pages");
      const outputFile = join(root, "src", "generated", "routes.tsx");

      server.watcher.add(pagesDir);
      server.watcher.on("all", (event, filePath) => {
        if (!filePath.startsWith(pagesDir)) return;
        if (event === "add" || event === "unlink") {
          generate(pagesDir, outputFile);
        }
      });
    },
  };
}
